# Generated by Django 5.1.4 on 2025-02-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='管理员备注', null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='is_admin_created',
            field=models.BooleanField(default=False, help_text='是否由管理员创建'),
        ),
    ]
